### PR TITLE
Update EL9 from 10.9.6 to 10.9.11

### PR DESCRIPTION
**Pull request by omadacat**

### CODE REVIEW

**Comment by omadacat** [comment]
I just need to grab sha512 for sources and it should be ready for merge
I checked the version my server is running though and it says 10.8.13, did i do something wrong? I dont seem to have gotten any updates from the repo at all.. The server runs on rocky linux 9.4. I'm not so sure if this is an issue with my end or rpmfusion's, im assuming its the first one

**Comment by kwizart** [comment]
Thanks for work on this PR on this. You might need to test in mock
Also we don't take comments in "sources" files

@mooninite for Review

**Comment by mooninite** [comment]
See RFBZ 6951 comment 8. Jellyfin 10.9 is not available for EL 8 or EL 9.

https://bugzilla.rpmfusion.org/show_bug.cgi?id=6951

**Comment by omadacat** [comment]
> Thanks for work on this PR on this. You might need to test in mock Also we don't take comments in "sources" files
> 
> @mooninite for Review

the 'comment' was meant to be a reminder to update the sha512 hash

> See RFBZ 6951 comment 8. Jellyfin 10.9 is not available for EL 8 or EL 9.
> 
> https://bugzilla.rpmfusion.org/show_bug.cgi?id=6951

is this anything someone can do, because this starting to become an annoying issue.
 As 10.8.X gets older, the features it supports dwindle. I did mention before the box runs on rocky therefore el9. Im already been given hard times by people trying to use updated clients and being told by the app that its not supported because of an over a year old update still being ran in prod.

**Pull request closed without merging**
